Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	1	mask_targets_catalogue
	1	run_tiling_equally_spaced
	3
Select jobs to execute...

[Tue Jun 15 15:36:03 2021]
rule mask_targets_catalogue:
    input: results/StarCatalogues/Panstarrs_match_Gaia_350_m20_targets.csv, resources/IDs_for_tile_selection/350_m22_equally_spaced_IDs.txt
    output: results/StarCatalogues/equally_spaced_350_m22.csv
    jobid: 2

[Tue Jun 15 15:36:04 2021]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Tue Jun 15 15:36:04 2021]
rule run_tiling_equally_spaced:
    input: config/Field_350_m20_equally_spaced.yaml, results/StarCatalogues/equally_spaced_350_m22.csv, results/StarCatalogues/Panstarrs_match_Gaia_350_m20_standards.csv, results/StarCatalogues/Panstarrs_match_Gaia_350_m20_guides.csv, results/SkyMasks/Mosaic/segmap_StarField_351.4_-22.fits
    output: results/TilingOutputs/350_m20_equally_spaced/completed_tiling.done
    jobid: 1

[Tue Jun 15 15:36:16 2021]
Error in rule run_tiling_equally_spaced:
    jobid: 1
    output: results/TilingOutputs/350_m20_equally_spaced/completed_tiling.done

RuleException:
CalledProcessError in line 79 of /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile:
Command 'set -euo pipefail;  /opt/anaconda3/envs/snakemake/bin/python3.9 /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/scripts/tmpmoj6iaah.run_tiling_equally_spaced.py' returned non-zero exit status 1.
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
  File "/Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/workflow/Snakefile", line 79, in __rule_run_tiling_equally_spaced
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 574, in _callback
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in cached_or_run
  File "/opt/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2390, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/samvaughan/Science/Hector/Targets/HectorInputCatalogues/Commissioning/StarFields/.snakemake/log/2021-06-15T153603.248104.snakemake.log
